openapi: 3.0.0
info:
  title: "GitHub Service"
  description: "Service to get all repositories and contributors from a GitHub oranization"
consumes:
  - application/json
produces:
  - application/json
